Fix storing ecr url to env.

diff --git a/.github/workflows/terraform-staging-apply.yml b/.github/workflows/terraform-staging-apply.yml
--- a/.github/workflows/terraform-staging-apply.yml
+++ b/.github/workflows/terraform-staging-apply.yml
@@ -42,8 +42,17 @@ jobs:
     - name: Capture ECR Repository URL
       id: ecr_output
       working-directory: terraform/staging
-      run: echo "ecr_repository_url=$(terraform output -raw ecr_repository_url)" >> $GITHUB_ENV
-
+      run: |
+        ecr_repository_url=$(terraform output -raw ecr_repository_url 2>/dev/null)
+        if [ -z "$ecr_repository_url" ]; then
+          echo "Error: ECR repository URL is empty or invalid."
+          exit 1
+        fi
+        echo "ecr_repository_url=$ecr_repository_url" >> $GITHUB_ENV
+      env:
+        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+    
     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
